# Generated by Django 5.1.15 on 2026-08-16 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_seed_platforms_regions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.TextField()),
                ("title", models.TextField()),
                ("link_name", models.TextField()),
                ("link_url", models.URLField(max_length=4096)),
                ("link_filename", models.TextField(blank=True)),
                ("link_host", models.CharField(blank=True, max_length=255)),
                ("link_size", models.BigIntegerField(default=0)),
                (
                    "link_source_id",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("link_requires_auth", models.BooleanField(default=False)),
                ("link_is_torrent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("downloading", "downloading"),
                            ("paused", "paused"),
                            ("extracting", "extracting"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("downloaded_bytes", models.BigIntegerField(default=0)),
                ("total_bytes", models.BigIntegerField(default=0)),
                ("bytes_per_second", models.IntegerField(default=0)),
                ("staged_file", models.TextField(blank=True)),
                ("playlist_file", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("failed_urls", models.JSONField(blank=True, default=list)),
                ("celery_task_id", models.CharField(blank=True, max_length=64)),
                ("group_key", models.TextField(blank=True)),
                ("group_title", models.TextField(blank=True)),
                ("group_index", models.IntegerField(blank=True, null=True)),
                ("group_total", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("first_retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.platform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="download_user_status_idx"
                    ),
                    models.Index(fields=["status"], name="download_status_idx"),
                ],
            },
        ),
    ]
