# Generated by Django 5.1.15 on 2026-08-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtask",
            name="link_torrent_file_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="downloadtask",
            name="link_torrent_magnet",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="downloadtask",
            name="torrent_hash",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
