# Generated by Django 5.1.15 on 2026-08-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0002_downloadtask_link_torrent_file_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtask",
            name="debrid_relink_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="downloadtask",
            name="debrid_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
