# Generated by Django 5.1.15 on 2026-08-18 20:13

from django.db import migrations, models


def backfill_region_ids(apps, schema_editor):
    """Fills the snapshot for tasks queued before it existed, by matching
    slug against the active build. A task whose entry has since been
    garbage-collected or re-slugged keeps [] — it just won't match a region
    filter; everything enqueued from here on is snapshotted at creation."""
    CatalogBuild = apps.get_model("catalog", "CatalogBuild")
    RegionEntry = apps.get_model("catalog", "RegionEntry")
    DownloadTask = apps.get_model("downloads", "DownloadTask")

    build = CatalogBuild.objects.filter(status="active").order_by("-started_at").first()
    if build is None:
        return

    tasks = list(DownloadTask.objects.all())
    if not tasks:
        return

    regions_by_slug: dict[str, list[str]] = {}
    pairs = RegionEntry.objects.filter(
        entry__build=build, entry__slug__in={t.slug for t in tasks}
    ).values_list("entry__slug", "region_id")
    for slug, region_id in pairs:
        regions_by_slug.setdefault(slug, []).append(region_id)

    for task in tasks:
        task.region_ids = regions_by_slug.get(task.slug, [])
    DownloadTask.objects.bulk_update(tasks, ["region_ids"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("downloads", "0004_downloadtask_download_user_slug_uniq"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtask",
            name="region_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_region_ids, migrations.RunPython.noop),
    ]
