# Generated by Django 5.1.15 on 2026-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0005_downloadtask_region_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("downloading", "downloading"),
                    ("paused", "paused"),
                    ("extracting", "extracting"),
                    ("converting", "converting"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
