# Generated by Django 5.1.15 on 2026-08-19 21:19

from django.db import migrations, models


def backfill_last_retrieved(apps, schema_editor):
    """Seed last_retrieved_at from first_retrieved_at.

    Without this, every download saved before this migration would show as
    never saved — the Library's Saved badge reads last_retrieved_at, and a
    user who has already worked through their list would watch their whole
    history blank out. One save is all that was ever recorded for these rows,
    so first and last are genuinely the same date.
    """
    DownloadTask = apps.get_model("downloads", "DownloadTask")
    DownloadTask.objects.filter(first_retrieved_at__isnull=False, last_retrieved_at__isnull=True).update(
        last_retrieved_at=models.F("first_retrieved_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0006_downloadtask_converting_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtask",
            name="last_retrieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Reverse is a no-op: rolling back drops the column outright.
        migrations.RunPython(backfill_last_retrieved, migrations.RunPython.noop),
    ]
