# Generated by Django 5.1.15 on 2026-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameMetadataCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.TextField(unique=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("no_match", models.BooleanField(default=False)),
                ("fetched_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
