# Generated by Django 5.1.15 on 2026-08-25 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0005_simple_search_vectors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RomSetDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(default="internet_archive", max_length=32),
                ),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("title", models.TextField()),
                ("emulator_id", models.CharField(blank=True, max_length=32)),
                (
                    "infohash",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("save_dir", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("fetching_metadata", "fetching_metadata"),
                            ("downloading", "downloading"),
                            ("paused", "paused"),
                            ("extracting", "extracting"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("total_bytes", models.BigIntegerField(default=0)),
                ("downloaded_bytes", models.BigIntegerField(default=0)),
                ("progress", models.FloatField(default=0.0)),
                ("bytes_per_second", models.IntegerField(default=0)),
                ("extract", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.platform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rom_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RomSetFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.TextField()),
                ("size", models.BigIntegerField(default=0)),
                ("wanted", models.BooleanField(default=True)),
                ("progress", models.FloatField(default=0.0)),
                ("done", models.BooleanField(default=False)),
                (
                    "romset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="romsets.romsetdownload",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.AddConstraint(
            model_name="romsetdownload",
            constraint=models.UniqueConstraint(fields=("user", "identifier"), name="romset_user_identifier_uniq"),
        ),
        migrations.AddConstraint(
            model_name="romsetfile",
            constraint=models.UniqueConstraint(fields=("romset", "path"), name="romsetfile_path_uniq"),
        ),
    ]
