# Generated by Django 5.1.15 on 2026-08-16 15:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("active", "active"),
                            ("retired", "retired"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                ("source_stats", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("brand", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["brand", "name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=128)),
                ("homepage", models.URLField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("catalog", "catalog"),
                            ("host", "host"),
                            ("hybrid", "hybrid"),
                        ],
                        max_length=16,
                    ),
                ),
                ("auth_required", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                ("manifest", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("slug", models.TextField(db_index=True)),
                ("rom_id", models.CharField(blank=True, max_length=64, null=True)),
                ("title", models.TextField(db_index=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("boxart_url", models.URLField(blank=True, max_length=2048, null=True)),
                ("ra_game_id", models.IntegerField(blank=True, null=True)),
                ("ra_num_achievements", models.IntegerField(blank=True, null=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="catalog.catalogbuild",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="catalog.platform",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
            },
        ),
        migrations.CreateModel(
            name="EntryGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("group_key", models.TextField()),
                ("kind", models.CharField(db_index=True, max_length=32)),
                ("title", models.TextField(blank=True, null=True)),
                ("member_count", models.IntegerField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_groups",
                        to="catalog.catalogbuild",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_groups",
                        to="catalog.platform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.entry"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.region"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entry",
            name="regions",
            field=models.ManyToManyField(
                related_name="entries",
                through="catalog.RegionEntry",
                to="catalog.region",
            ),
        ),
        migrations.CreateModel(
            name="SourceHealth",
            fields=[
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="health",
                        serialize=False,
                        to="catalog.source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("entry_count", models.IntegerField(default=0)),
                ("link_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Torrent",
            fields=[
                (
                    "infohash",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=512, null=True)),
                ("magnet", models.TextField(blank=True, null=True)),
                (
                    "torrent_file",
                    models.FileField(blank=True, null=True, upload_to="torrents/"),
                ),
                ("total_size", models.BigIntegerField(blank=True, null=True)),
                ("piece_length", models.IntegerField(blank=True, null=True)),
                ("file_count", models.IntegerField(blank=True, null=True)),
                ("trackers", models.JSONField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="torrents",
                        to="catalog.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("type", models.CharField(blank=True, max_length=32)),
                ("format", models.CharField(blank=True, max_length=16)),
                ("url", models.URLField(max_length=4096)),
                ("filename", models.TextField(blank=True)),
                ("host", models.CharField(blank=True, max_length=255)),
                ("size", models.BigIntegerField(default=0)),
                ("size_str", models.CharField(blank=True, max_length=32)),
                ("source_url", models.URLField(blank=True, max_length=4096, null=True)),
                ("requires_auth", models.BooleanField(default=False)),
                ("torrent_file_index", models.IntegerField(blank=True, null=True)),
                ("torrent_file_path", models.TextField(blank=True, null=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="catalog.entry",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links",
                        to="catalog.source",
                    ),
                ),
                (
                    "torrent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links",
                        to="catalog.torrent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntryGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_index", models.IntegerField(blank=True, null=True)),
                (
                    "member_label",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="catalog.entry",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="catalog.entrygroup",
                    ),
                ),
            ],
            options={
                "ordering": ["member_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "entry"), name="unique_group_member"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="entrygroup",
            constraint=models.UniqueConstraint(
                fields=("group_key", "build"), name="unique_entry_group_key_per_build"
            ),
        ),
        migrations.AddIndex(
            model_name="regionentry",
            index=models.Index(fields=["entry"], name="region_entry_entry_idx"),
        ),
        migrations.AddIndex(
            model_name="regionentry",
            index=models.Index(fields=["region"], name="region_entry_region_idx"),
        ),
        migrations.AddConstraint(
            model_name="regionentry",
            constraint=models.UniqueConstraint(
                fields=("entry", "region"), name="unique_region_entry"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="entry_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["platform"], name="entry_platform_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["build"], name="entry_build_idx"),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("slug", "build"), name="unique_entry_slug_per_build"
            ),
        ),
        migrations.AddIndex(
            model_name="link",
            index=models.Index(fields=["entry"], name="link_entry_idx"),
        ),
        migrations.AddIndex(
            model_name="link",
            index=models.Index(fields=["source"], name="link_source_idx"),
        ),
        migrations.AddIndex(
            model_name="link",
            index=models.Index(fields=["torrent"], name="link_torrent_idx"),
        ),
    ]
