# Generated by Django 5.1.15 on 2026-08-16 20:18

import apps.common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("internet_archive", "internet_archive"),
                            ("realdebrid", "realdebrid"),
                            ("torbox", "torbox"),
                            ("screenscraper", "screenscraper"),
                            ("steamgriddb", "steamgriddb"),
                        ],
                        max_length=32,
                    ),
                ),
                ("data", apps.common.fields.EncryptedJSONField()),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "unverified"),
                            ("ok", "ok"),
                            ("stale", "stale"),
                            ("invalid", "invalid"),
                        ],
                        default="unverified",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider"),
                        name="unique_user_provider_credential",
                    )
                ],
            },
        ),
    ]
